### ISSUE TITLE
Contour error when plot contains no events, analysis stops/not possible

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#104]
If there is zero data points in a data set or all points were gated out ShapeOut doesn't work anymore. It would be best if the plots would show a caption like "no data" instead.

**Comment by paulmueller** [comment]
I fixed this in a8d3efc65a21b6f8f57d92cf64613ac7d01bfe2b. The problem was that contours could not be computed. In my opinion, displaying "no data" is not necessary. You can see the number of events at the top right of the plot. This should be enough.
