### ISSUE TITLE
Add link to documentation

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#109]
Put this in the readme and possibly also bundle it with ShapeOut.

~~http://www.zellmechanik.com/media/tyfd186-7aceba77eaa62786b8942ee9085af159/Instructions_ShapeOut.pdf~~

http://www.zellmechanik.com/Download.html

**Comment by paulmueller** [comment]
@DerDeef Would it not be possible to have a static link to the documentation?

**Comment by DerDeef** [comment]
Hi Paul. Ich frag mal unseren Webseitenhost. Warum geht das nicht mit nem normalen Link?

**Comment by paulmueller** [comment]
Weil, wenn ihr eine neue Version der Datei hochladet, der Link nicht mehr stimmt. Es wäre unnötiger Aufwand, das immer aktualisieren zu müssen.

**Comment by DerDeef** [comment]
hi. ja, das selbe sagen mir die webseiten-dudes... das dokument bekommt bei denen ne ID sodass es auch gefunden wird wenn man die webseite umbaut... und damit isses nicht statisch. es direkt beim hoster hinzulegen, kann ich nicht. Also, ganz anders: kannst du in die README relativ am Anfang schreiben: Manual/User Guide at www.zellmechanik.com/download
fertig, ok?
