### ISSUE TITLE
All Downsampling of data

### ISSUE THREAD

**Issue by Naven2812** [ZellMechanik-Dresden/ShapeOut#11]
Downsample data to a number of events given by user, e.g. all samples have the same number of data points

**Comment by Naven2812** [comment]
Downsample on data not on display

**Comment by paulmueller** [comment]
Why would you want this? Faster computation time?
It would certainly change the kernel densities / contour plots.

**Comment by Naven2812** [comment]
No, to make sure every data set has same number of events (not display)

**Comment by phidahl** [comment]
But why not on display? - I think it would only make sense to display the dataset ShapeOut is actually working on.

**Comment by paulmueller** [comment]
New option available in 0.4.6
