### ISSUE TITLE
New Tool: Convert tdms files to fcs

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#112]
Version 0.6.7 allows to export data to fcs files.

Would it be useful to have a tool built-in in ShapeOut that can convert tdms files directly to fcs files?
I already implemented it here:
https://github.com/ZELLMECHANIK-DRESDEN/fcswrite/blob/master/examples/tdms2fcs.py

Let me know what you think.

**Comment by phidahl** [comment]
As far as I heard from those using it, this feature seems to work.

**Comment by paulmueller** [comment]
The question is, whether a conversion tool should be implemented in ShapeOut in a drag-and-drop style fashion.

**Comment by paulmueller** [comment]
There seems to be no interest. I am closing this one.
