### ISSUE TITLE
Disable kernel density estimation / contour plot by default

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#116]
Due to speed issues (please try the latest version 0.6.8 before you comment), ShapeOut can become quite slow at times. Would it make sense to disable the coloring of the scatter plots by default and/or disable the contour plots by default?

**Comment by MartaUrb** [comment]
It may make sense, especially for the situation when one has datasets of 15000 events or more the density estimator takes lots of time and may be not necessary. Yet, one can disable both KDE and contour plot before analysing the data so if one knows it may be the problem it can be prevented. I guess it is a bit difficult to say what is the most frequent scenario for average user (few datapoints and quick access to contours wanted or big datasets and no need of KDE/contours)

**Comment by katpla** [comment]
Other option would be to include a choice to Analyze button. For example once you hit STANDARD ANALYZE - you get traditional shapeout plots with color coded densities, contour plots etc. If you hit FAST ANALYZE you get the plot with black points, no contours and whatever else makes it fast for plotting. After doing fast analyze one can then do all the filtering etc before going for contours.

**Comment by phidahl** [comment]
Switch. It. Off. by default.

its not that important. in facs software there is an extra function to make plots look nice.
