### ISSUE TITLE
Fluorescence traces not shown in 0.6.8.dev8

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#118]
This is something new to the current development version (Appveyor).
Running on a Win7 PC.

No error message.

This scale of the y-axis is adjusted, but there are not datapoints loaded into the plot. x-axis is blank.

**Comment by paulmueller** [comment]
This error does not occur with 0.6.8.dev7 and 0.6.8.dev6?

**Comment by phidahl** [comment]
This error also occurs in 0.6.8.dev6.

**Comment by paulmueller** [comment]
Ok, and it worked in the release 0.6.8? There were some speed-ups in that release which might have worked on Linux, but not on Windows. Thanks for testing.

**Comment by phidahl** [comment]
In release 0.6.8 it still works.

**Comment by paulmueller** [comment]
This bug only occured with specific trace data. It should be fixed now.
