### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#12]
Analyse where the program spends time.
Could it be that the KDE is taking a lot of time for larger datasets? - > Find a more performant way for estimating the densities (e.g. histogram 20 x 20 bins)

When importing and analyzing larger datasets, the ShapeOut gets quite slow.

**Comment by paulmueller** [comment]
If you run ShapeOut from source you will see timing information printed to the terminal.
Binning to 2D histograms could be a fast option.

**Comment by paulmueller** [comment]
reference:
https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/2

**Comment by paulmueller** [comment]
this is implemented now
