### ISSUE TITLE
Linear mixed model R-package missing

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#120]
If I select a dataset for the linear mixed-effects model, I get the following error message (Win7 0.6.8dev8 from Appveyor)

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.controls_analysis", line 119, in OnApply
  File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.lin_mix_mod", line 265, in linmixmod
OSError: R installation at C:\Program Files\R\R-3.3.0\bin\i386\R.exe: try({library(lme4)})
Error in library(lme4) : es gibt kein Paket namens 'lme4'

Please install 'lme4' via:
              C:\Program Files\R\R-3.3.0\bin\i386\R.exe -e "install.packages('lme4', repos='http://cran.r-project.org')
              

[OK]

**Comment by paulmueller** [comment]
It looks like ShapeOut is using your local R installation instead of the one that it ships with. This is actually a feature, which, if everyone agrees, we can remove. Running the install command for lme4 would solve the problem.

**Comment by phidahl** [comment]
Ok.

I would agree, that ShapeOut should only use its own R.
