### ISSUE TITLE
Invert polygon filters

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#127]
For applications where a parameter is used to divide cells in positive/negative fractions it would be great to have the a function to invert a given polygon filter.

Ideal would be:
- select an existing polygon filter
- click "create inverted copy" or similar
- a new polygon filter shows up in the list, which is the inverted version of the existing polygon filter

Best.
Philipp

**Comment by paulmueller** [comment]
Inversion is implemented now. Please test:
https://ci.appveyor.com/project/paulmueller/ShapeOut/build/job/f6pe8bs4pp4mwu1k/artifacts
