### ISSUE TITLE
Video Frame Offset = 0

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#130]
In a measurement where the first frame in the _imaq.avi file corresponds to the first line in the .tdms file the contours are not shown.
in the para.ini file Video Frame Offset = 0 is set.

**Comment by paulmueller** [comment]
I cannot reproduce this bug. Could you please upload an example data set somewhere?

**Comment by phidahl** [comment]
I now found da dataset with which it was also working ok. It must be something else.. I'll find out. Sorry.
