### ISSUE TITLE
batch processing, only chosen flowrate

### ISSUE THREAD

**Issue by katpla** [ZELLMECHANIK-DRESDEN/ShapeOut#132]
Hello,

would it be possible to make a small change to batch processing mode? Here an example of the problem:

I need to run batch processing on large no of files contained in one folder. 
In this folder there are regular measurements and reservoir measurements.
I do not want to run the batch processing on reservoir measurements (or alternatively I only want to run batch analysis on a specific flowrate, example 0.04ul/sec)

In general what I would like to be able is to choose a specific flowrate from the batch analysis setup window.

Thanks
K

**Comment by paulmueller** [comment]
Yes, in principle, this is possible.
However, since you have the option to export the flow rate and can perform this step after batch processing, I will not give it high priority.
What is your largest concern here. Performance or cleanliness of the exported tsv file?

**Comment by katpla** [comment]
Hi,
Ok, for the low priority.

Here the explanation:
the problem are the filters. the filters that i am using are based on fluorescence parameters as peak width. Peak width depends on the cell speed (flowrate) so the filters are only true for given flowrate. The reservoir is a whole other problem as most of the cells in reservoir do not have fluorescent value (region of interest for the camera is much larger than the region of fluorescence detection).

There is one more thing about my particular case which has to do with two additional columns I have in tdms files for flowrate1 and flowrate2 but not in reservoir files. I would like to include the two userdef columns in batch processing analysis, however as they are missing in reservoir I tend to get a problem.

I think I can work around this second problem however.

Thanks

**Comment by paulmueller** [comment]
Ok. As far as I understand, you would like to avoid garbage (and the associated manual sorting) in the exported tsv files.
For your second problem: If the userdef columns are not in the reservoir files, then batch processing should export these values as "nan"s. If this is not the case, please open an additional issue.

**Comment by katpla** [comment]
I am not 100% sure what was the problem i have been dealing with here. I tried some small datasets with the userdef1 column missing and indeed those got "nan" values.
I think maybe the problem was appearing if the filter settings resulted in 0 cells left? Anyhow after removing 'bad' datasets the batch analysis works

**Comment by paulmueller** [comment]
I implemented this functionality. It will be available in the next release. Could you please test it?
https://ci.appveyor.com/project/paulmueller/ShapeOut/build/job/ve6w01fsko585wr3/artifacts
