### ISSUE TITLE
Set new histogram-based KDE as default?

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#133]
dclab now comes with a new histrogram-based KDE. It is orders of magnitude faster than the Gaussian or Multivariate methods. Should we set it as the new default KDE instead of "none"?
[gauss.pdf](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/files/811655/gauss.pdf)
[histogram.pdf](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/files/811654/histogram.pdf)

@phidahl

**Comment by phidahl** [comment]
I think we should. What does Christoph think?

**Comment by paulmueller** [comment]
@chrherold

**Comment by chrherold** [comment]
I would like the histogram option as default very much.
