### ISSUE TITLE
Default location for "Add Measurements" and "Find Measurements" dialogs

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#139]
If one clicks File->Find Measurements one ends up in the last folder opened which is convenient in many cases.

If on clicks File->Add Measurements one always ends up on the Desktop. It gets very tedious to add multiple folders this way.

I would propose that both dialogs share a "last folder opened" variable which is then used as starting point for the dialog.

**Comment by paulmueller** [comment]
Thanks, your proposal is actually the intended default behaviour.
