### ISSUE TITLE
bug during opening saved sessions

### ISSUE THREAD

**Issue by katpla** [ZELLMECHANIK-DRESDEN/ShapeOut#141]
There appears to be a problem when saved sessions are opened again in shapeout. If the number of stored measurements is >9 the shapeout does not open the saved session (at least not withing 10-15 minutes). If the number of measurements is 9 or less then the problem does not occur.

We saw this for measurements of different cell number so it seems not to be related to the amount of events in the data sets.
The problem is also not limited to the latest software release,

**Comment by paulmueller** [comment]
Thanks, I fixed it in the develop branch.

**Comment by katpla** [comment]
it does work now
