### ISSUE TITLE
Linear Mixed Effects Models in Python instead of R?

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#144]
I think it would make sense to migrate the computation of linear mixed effects models from R to Python. The R installation seems to continuously make trouble, blows up the size of the Windows installer and makes it difficult to understand, test, and use the code. `statsmodels` seems to have this capability:

http://statsmodels.sourceforge.net/devel/mixed_linear.html

@MaikH88 
Could statsmodels replace the current R workflow?

**Comment by MaikH88** [comment]
Finally linear mixed models are also available in statsmodels! I was able to reproduce the exact same results in lme4 and statsmodels for an example dataset using linear mixed models.
Unfortunately generalized linear mixed models are not yet available. Therefore I would not yet switch.
On the one hand it is nice that users can currently check their ignificance values at least using two models. On the other hand lmm and glmm give very similar results for us becasue lmm is already quite robust for non-normal data.

**Comment by paulmueller** [comment]
Thanks for the comment - good to know. I suggest we wait until glmm is in statsmodels. Are there any other opinions?

**Comment by paulmueller** [comment]
Unlikely that anything is going to change here, because the focus us on Shape-Out 2.
