### ISSUE TITLE
New isoelastics (analytical and FEM)

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#145]
ShapeOut is able to compute the elastic modulus using a look-up table computed from simulations.

See

Numerical Simulation of Real-Time Deformability Cytometry To Extract
Cell Mechanical Properties
M. Mokbel, D. Mokbel, A. Mietke, N. Träber, S. Girardo, O. Otto, J.
Guck, and S. Aland
ACS Biomaterials Science & Engineering Article ASAP
DOI: 10.1021/acsbiomaterials.6b00558

Currently, the isoelastics are computed using an analytical model (Mietke et al.). There are slight differences in the resulting elastic modulus. One solution would be to compute the isoelastics the same way the emodulus is computed.  @chrherold

**Comment by chrherold** [comment]
I guess it would be best to keep both options not to hinder continuity.

I will calculate a set of isoelastics from the simulation, including all corrections for pixel deviation.

But the purely theoretical isoelastics should be available as well.

Which leads me to a bug report on version 0.7.8 (and possibly earlier) where
isoelastics are no longer plotted, even if checked.

**Comment by paulmueller** [comment]
Having both options is fine with me. Once we have the data, I will move the isoelastics code to dclab and add proper testing.

Looks like the isoelastics-not-shown bug is present since the refactoring that took place in 0.7.6. I meant to move the isoelastics code from ShapeOut to dclab earlier, but I wanted to wait until the new isoelastics were available.
In the latest build, the isoelastics should be visible again (see commit above):
https://ci.appveyor.com/project/paulmueller/ShapeOut/build/job/ddsculiyw3uxp226

**Comment by chrherold** [comment]
Isoelastics are back in action. Thanks for the quick fix!

I'll prepare the simulated ones asap.

**Comment by paulmueller** [comment]
@chrherold 
Isoelastics have now moved to dclab. When you create a new set of isoelastics with FEM, please follow the style/format of the isoelastics from the analytical model:

https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/isoelastics/isoel-analytical-area_um-deform.txt

You can reuse the header from the LUT for emodulus computation:

https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/features/emodulus_lut.txt

It also might make sense to compute another set of analytical isoelastics for a broader range of emoduli. And it probably makes sense to compute the isoelastics for the analytical model and the FEM model for the same range of area and deformation (as long as the model is valid there) and for the same emoduli. This will make it easier to compare the two and it would look professional in ShapeOut.
