### ISSUE TITLE
Histogram coloring of points

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#147]
ShapeOut 0.7.3 (release)

produces the following plots with obviously wrong densitiy estimation. Histogram KDE is selected.

![new bitmap image](https://cloud.githubusercontent.com/assets/12835020/25386266/139a64a0-29c7-11e7-86bf-b5ee6a5e1cff.png)

P.S. happy birthday :)

**Comment by paulmueller** [comment]
This looks to me like an inherent binning problem. Have you tried decreasing the "kde accuracy" parameters in the "Contour Plot" tab? We could try to change the default parameters for the histogram KDE, but then we should also change them for multivariate and gauss such that the KDE looks similar for all of them.

**Comment by phidahl** [comment]
Yes, this helps.

Choosing:
kde accuracy area: 5
kde accuracy defo: 0.01

gives me better plots. @chrherold could you please confirm these values?
@paulmueller: I think we should set the std values for contour accuracy to the same.

Best
Philipp

**Comment by paulmueller** [comment]
As suggested by @maikherbig, the accuracies are now computed according to Doane's formula. The contour accuracy is set to half (better) of the kde accuracy. I thought the plots look nicer this way. Please test:

https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.846/job/ks8pdk48m930dqtt/artifacts
