### ISSUE TITLE
Cannot load my old session files anymore

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#152]
When loading session files (created in ... Dec 2016, so it should be created with ShapeOut 0.6.8) it get an error, that might have to do with the filters, I set in the session.

The latest version that works is ShapeOut 0.7.0.
ShapeOut 0.7.1 and 0.7.2 and the latest dev Version (64bit and 32bit) are broken.

With ShapeOut 0.7.1 I get:

> [Window Title]
> Error
> 
> [Content]
> Traceback (most recent call last):
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.frontend", line 475, in OnMenuLoad
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.session", line 232, in open_session
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.frontend", line 344, in NewAnalysis
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.plot_main", line 60, in Plot
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.plot_main", line 124, in Plot
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.plot_scatter", line 121, in scatter_plot
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\shapeout.gui.plot_scatter", line 253, in set_scatter_data
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\dclab.rtdc_dataset.core", line 484, in get_downsampled_scatter
>   File "C:\projects\shapeout\build\win_shapeout\out00-PYZ.pyz\dclab.rtdc_dataset.core", line 365, in ApplyFilter
> KeyError: u'UserDef1'

**Comment by paulmueller** [comment]
Please give me the session file and one of the measurement files. There might just be a ".lower()" missing somewhere.

**Comment by phidahl** [comment]
Here you are. zipped because of github..

[p1234_mc_vergleich_FINAL_RETchilds.zmso.zip](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/files/1023665/p1234_mc_vergleich_FINAL_RETchilds.zmso.zip)

**Comment by paulmueller** [comment]
Please check with the latest dclab version. If the problem persists, please reopen this issue.
