### ISSUE TITLE
Add expert mode

### ISSUE THREAD

**Issue by chrherold** [ZELLMECHANIK-DRESDEN/ShapeOut#157]
...for experimental column names and other functionalities.

**Comment by paulmueller** [comment]
In expert mode, the following columns will become visible: "area_cvx", "area_msd", "frame"
https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/blob/a0b2f1806b5b6ef26222b4c2fe028de1b8c1b1a1/shapeout/tlabwrap.py#L461
