### ISSUE TITLE
Display contour plot broken

### ISSUE THREAD

**Issue by maikherbig** [ZELLMECHANIK-DRESDEN/ShapeOut#160]
Hi,
when I load a measurement, go to "contour plot", tick the checkbox "contourplot" and use any KDE I get an error message in version 0.7.6 ("RTDC_TDMS object has no attribte 'name'"). In version 0.7.5 it works fine.
![problem_contour](https://user-images.githubusercontent.com/14074051/28114984-6b47cf84-6703-11e7-9496-b4cdc046a32e.png)

**Comment by paulmueller** [comment]
Thanks for reporting and sorry for the inconvenience. Please try the latest build:
https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.662/job/i0mo8l44wv6s5h4k/artifacts
(This bug was caused by refactoring in dclab.)

**Comment by maikherbig** [comment]
Fantastic! It works now :)
