### ISSUE TITLE
Error: Contour data has unknown offset

### ISSUE THREAD

**Issue by maikherbig** [ZELLMECHANIK-DRESDEN/ShapeOut#166]
When I load the attached data into ShapeOut, select M1 and hit analyze there pops up an error message saying: IndexErrror: Contour data has unknown offset
I attached the measurement where that happens
[Online.zip](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/files/1164818/Online.zip)

**Comment by paulmueller** [comment]
I cannot reproduce this bug on Linux. If it is a Windows-specific problem, the latest build could work:
https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.685

(dclab 0.2.5dev5 https://github.com/ZELLMECHANIK-DRESDEN/dclab/commit/81b18e2a5ed3a0eb46ee52fd0d280f6847033dce)

**Comment by maikherbig** [comment]
Unfortunately, the problem persists:
![error](https://user-images.githubusercontent.com/14074051/28457012-b5c0c446-6e04-11e7-872b-51652fd08754.png)

**Comment by paulmueller** [comment]
Does this bug only occur for the uploaded data or for all data loaded into ShapeOut?

**Comment by maikherbig** [comment]
just for the uploaded

**Comment by paulmueller** [comment]
Please try the latest build: https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.692
