### ISSUE TITLE
Event contours are drawn at wrong position for large field of views

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/ShapeOut#167]
If one measures with ROIs larger than 250 pixels in width, the contours will be only drawn into the first 250 pixels of the image. This might cause funny effects like shown in the image below.  

![capture_shapeout](https://user-images.githubusercontent.com/19806005/28571523-880de1cc-7143-11e7-9375-8af044ccaf52.PNG)

**Comment by paulmueller** [comment]
Could it be that these are the first 256 pixels of the image? In that case, this might be a problem in ShapeIn, storing the contour coordinates as uint8 @phidahl?

We could implement a workaround for the tdms file format, if this is critical (e.g. if you need to compute emoduli).

**Comment by phidahl** [comment]
Check the txt files where the contours are. it should be 32bit and then stored in an asci file.

Von meinem Telefon gesendet

**Comment by paulmueller** [comment]
@felix-r Could you please upload the "M*_contours.txt" file of  that particular measurement here or point us to an internal location where to find your data?

**Comment by felix-r** [comment]
This is the contours-.txt-file for example above.

[M14_0.024000ul_s_contours.txt](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/files/1176654/M14_0.024000ul_s_contours.txt)

**Comment by paulmueller** [comment]
Ok, it's not a ShapeIn bug. I would need the full measurement to debug this (including the avi file). Anywhere on the group drive is fine.

**Comment by felix-r** [comment]
It's here: \\biotec-files\guck_rtdc\experiments_16_17\20170725_Ruchi_PAA_Beads\PAA_220517_S0_3(1)\Online

The example measurement is M14

**Comment by paulmueller** [comment]
This was a bug in dclab (see commit message above). Please try the latest release:
https://ci.appveyor.com/project/paulmueller/ShapeOut/build/job/khksjp01br3x2ib4/artifacts
