### ISSUE TITLE
ShapeOut 0.7.8: Error message: Contor data has unknown offset 

### ISSUE THREAD

**Issue by maikherbig** [ZELLMECHANIK-DRESDEN/ShapeOut#169]
The following Error-message pops up in ShapeOut 0.7.8 for a specific measurement. Everything is working fine in version 0.7.7
![error](https://user-images.githubusercontent.com/14074051/28770621-25e511c2-75e0-11e7-8738-ef85e2bf6263.png). Should I do further tests, when the error occurs?

**Comment by paulmueller** [comment]
Yes, please. If this is related to #166, then the problem might caused by the `contour*.txt` filenames. You could try renaming them to just "M1_contours.txt". Please point me to a location of the measurement so I can have a look.

**Comment by maikherbig** [comment]
- https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.692 does not fix the problem
- renaming to "M1_contours.txt" does not fix the problem
-Only having a single measurement in the Online folder fixes it (this is not a good solution I think)
Here are the files:
[test2.zip](https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/files/1187367/test2.zip)

Many many thanks in advance!

**Comment by paulmueller** [comment]
Found it, there was a type.

**Comment by paulmueller** [comment]
New binaries for ShapeOut 0.7.8 are being built with dclab 0.2.6dev1. These should work.
