### ISSUE TITLE
error reading session files

### ISSUE THREAD

**Issue by katpla** [ZELLMECHANIK-DRESDEN/ShapeOut#176]
Hello,

I have troubles opening my session files today - last time I worked with them was less than 48h ago and all was working well. Today I get errors (all session files that are corrupted are saved on one common analysis computer - where other people may have admin privileges and could change something as I wasn't there). The session files once transferred to new computer cannot be opened either (confirmed on two computers). I tried sending a working session file from my laptop to the analysis computer - this also failed to open but with a yet different error. Any clues n what is up?

I am not sure how to upload session files here but the error message reads - 
File "gui\frontend.py", line 505, in OnMenuLoad
File "gui\session.py", line 48, in open_session
File "gui\session.py", line 4, in open_session_worker
File "zipfile.py", line 770, in _init_
File "zipfile.py", line 813, in _RealGetContents
BadZipfile: File is not a zip file

**Comment by paulmueller** [comment]
It is unlikely that someone else did something to the session files. This looks like the file system is corrupt or the disk is broken. To clarify what is happening, could you please

1. Make sure that you can save and open a session with ShapeOut on that PC. Did you override the session files 48 hours ago or did you just open them and not save them again?
2. See if there are any other files stored on that PC that cannot be opened (e.g. text files). If this is the case, then the disk might be broken.
3. Send me one of the broken session files.
4. Did you upgrade ShapeOut lately? Try using a previous version of ShapeOut. If we are lucky, then this is just a compatibility problem between different versions of Python/zipfile which could be fixed.

**Comment by katpla** [comment]
Good catch. I contacted other users and apparently there were issues with
other ppl files yesterday. We will have IT support over here look at the
machine.
Thanks for help!

**Comment by katpla** [comment]
That of course means everything fine with shapeout and the issue can be
closed

**Comment by paulmueller** [comment]
ok, closing for now.
