### ISSUE TITLE
Compensation for fluorescence data

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#185]
For multichannel fluorescence measurements we need a way to compensate the fluorescence max. values.

Compensations means to take account for channel crosstalk by subtraction of an adjustable fraction of other channels from the values of one channel.

The corrections factors can be expressed by a (NxN) matrix A

fl1_max' = fl1_max - A_12 * fl2_max - A_13 * fl3_max
fl2_max' = fl2_max - A_21 * fl1_max - A_23 * fl3_max
fl3_max' = fl3_max - A_31 * fl1_max - A_32 * fl2_max

It would need a some edit fields to adjust the values of A_xy and a checkbox to switch compensation on/off.

**Comment by paulmueller** [comment]
Instead of a checkbox, would it be ok if we created new data columns for this purpose ("FL-1 maximum, cross-talk-corrected [a.u.]")?
Do you need this for the raw trace data as well?

**Comment by phidahl** [comment]
new data columns would be even better.
Nope, the trace data shall be unaffected. (for now)

**Comment by paulmueller** [comment]
This is implemented in ShapeOut 0.8.1.dev21.
Please test:
https://ci.appveyor.com/project/paulmueller/ShapeOut/build/job/hb3l29qq79d8pu64/artifacts

**Comment by phidahl** [comment]
I tested it and it seems to work.
Thank you
