### ISSUE TITLE
FCS export broken

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#189]
I get this error message:

[Window Title]
Error

[Content]
Traceback (most recent call last):
  File "shapeout\gui\export.py", line 138, in OnBrowse
  File "shapeout\gui\export.py", line 168, in export
  File "site-packages\dclab\rtdc_dataset\export.py", line 130, in fcs
  File "site-packages\fcswrite\fcswrite.py", line 154, in write_fcs
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb3' in position 2491: ordinal not in range(128)

[OK]

**Comment by paulmueller** [comment]
There is probably an ascii character in the header. I think I fixed it in fcswrite. Could you please test the latest commit?

https://ci.appveyor.com/project/paulmueller/ShapeOut/build/job/n3srgjrm5jxaw6db/artifacts

**Comment by phidahl** [comment]
The lates build does not start. 
„Failed to execute script ShapeOut“



Von meinem Telefon gesendet

**Comment by paulmueller** [comment]
Sorry, I moved some io operations to pathlib which didn't get included in the installer. Please try again:
https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.785/job/7qsvnf7ab9d9kxk5
