### ISSUE TITLE
Error in ShapeOut

### ISSUE THREAD

**Issue by OttoOliver** [ZELLMECHANIK-DRESDEN/ShapeOut#194]
Fluorescence Gating and setting area ratio filter to 1.1 does not work in current version. ShapeOut crashes completely.

**Comment by paulmueller** [comment]
Could you please point me to the data with which you experience this problem? How are you gating (using the min/max box filters or the polygon filters)?

**Comment by OttoOliver** [comment]
Thanks Paul, We use only min max after compensating. Should I send you the data set?

**Comment by paulmueller** [comment]
Yes, please. I am unable to reproduce this with my current test data set.

**Comment by paulmueller** [comment]
Please let me know if this has been fixed with issue #195.

**Comment by OttoOliver** [comment]
With the new software the error does not occur. Thanks

**Comment by paulmueller** [comment]
Ok, closing this one.
