### ISSUE TITLE
Plotting with log-scale causes undefined error when plotting minimum is zero

### ISSUE THREAD

**Issue by OttoOliver** [ZELLMECHANIK-DRESDEN/ShapeOut#195]
FLuorescence shows no ticks on axes. Could you please adjust min value to 1. This helps. Thanks

**Comment by paulmueller** [comment]
I cannot reproduce this on Linux; might be Windows-related.

**Comment by chrherold** [comment]
Hi, could it be there are negative or zero data and you are plotting in log scale with auto-selection of the min and max?

Could you try setting boundaries for plotting between 1 and 35000?

Possibly we should work out a way to have a pseudo log plotting for values < or = 0.
Currently the only option to display those values is linear plotting.

**Comment by paulmueller** [comment]
In that case, would ignoring values <= 0 before plotting be an acceptable solution?

**Comment by chrherold** [comment]
If they are completely ignored gating for "zero" fluorescence values would be problematic.
I guess it would be ok if <= 0 values would be ignored in finding the plotting boundaries in log scale plotting, to get rid of the state where no scale ticks are applied to the plot axis.

In ShapeIn any negative or zero values are displayed as 1 just not to loose them in the log display. But of course this is only a half measure.

**Comment by OttoOliver** [comment]
Maye I was not specific. When you set min=1 in Ploting everything works. Could you set this automatically when log-scale is selected? Thanks

**Comment by paulmueller** [comment]
Yes, I guess this would make sense only for fluorescence data. For other data, I guess something like two times the log-std below the log-median should work well.

**Comment by OttoOliver** [comment]
Fluorescence would be fine. Thanks Paul

**Comment by paulmueller** [comment]
This is now implemented in the development version. Could you please test it?

https://ci.appveyor.com/api/buildjobs/1hlrytx0x5e1vd32/artifacts/.appveyor%2FOutput%2FShapeOut_0.8.2.dev12_win_64bit_setup.exe

**Comment by OttoOliver** [comment]
Dear Paul, it is better now but not great. Would it be possible to display the min and max when plotting fluorescence? It seems that the software chooses some scale.

**Comment by paulmueller** [comment]
I am not sure I understand what you are asking for. Do you want the range shown in the "Plotting" tab to update when you switch to logarithmic scale? This might cause confusion when you want to go back to linear scale and negative values are not displayed anymore. Let me know what you think.

You can always manually change the the displayed range (min/max) in the "Plotting" tab. ShapeOut uses the first scatter plot to determine the displayed range if the min/max values do not make sense (e.g. min=max=0 or min=0 for a log plot).

If you drag the scatter plot with the mouse, the x-y-range displayed in the "Plotting" tab is updated.

**Comment by paulmueller** [comment]
I am moving the feature request regarding the update of the plotting parameters to a new issue: #198
