### ISSUE TITLE
Update Plotting Range displayed in "Plotting" tab when switching to log scale 

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#198]
Do you want the range shown in the "Plotting" tab to update when you switch to logarithmic scale? This might cause confusion when you want to go back to linear scale and negative values are not displayed anymore. Please let me know what you think.

You can always manually change the the displayed range (min/max) in the "Plotting" tab. ShapeOut uses the first scatter plot to determine the displayed range if the min/max values do not make sense (e.g. min=max=0 or min=0 for a log plot).

If you drag the scatter plot with the mouse, the x-y-range displayed in the "Plotting" tab is updated.

**Comment by chrherold** [comment]
I guess it is best if the range that is displayed is always correct. So it should be updated to be 1 when changing to log scale if it was 0 or below before.

**Comment by paulmueller** [comment]
The displayed plotting range is now always automatically updated. As a result, setting both min/max values to zero (for maximal plotting range) does not work anymore and I had to make ShapeOut forget the previous plotting range when the user starts a new analysis. Please check whether this behaviour is ok:

https://ci.appveyor.com/project/paulmueller/shapeout/build/job/7v86b2vkkn4i245y/artifacts

**Comment by paulmueller** [comment]
TODO:
- [ ] To regain the previous behavior, add a checkbox "fix plotting range".
