### ISSUE TITLE
Frozen Insert field in Calculate Tab

### ISSUE THREAD

**Issue by maikherbig** [ZELLMECHANIK-DRESDEN/ShapeOut#206]
Hi,
When I enter some values in the "Calculate Tab" and hit "Compute Elastic Modulus" or "Crosstalk compensation", the fields become blanc (but the action is executed). If I need to change the values there, I need to go to an arbitrary other tab and hit "Apply" to force a refreshing of the panel. 
![error](https://user-images.githubusercontent.com/14074051/36117025-894d26e4-1038-11e8-9ede-500cd2329a9d.png)

**Comment by paulmueller** [comment]
Although I cannot reproduce this on Linux, I might have fixed it in the development version. Please try this build and let me know whether the problem persists (might have to wait until the build job finishes):

https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.835/job/d9eksdd8bho65i8r/artifacts

**Comment by maikherbig** [comment]
Unfortunately, it still happens

**Comment by paulmueller** [comment]
sorry, I accidentally closed this one.

**Comment by paulmueller** [comment]
I cannot reproduce this on Windows 10. Are you using Windows 7 or can you reproduce this bug on other computers?

**Comment by paulmueller** [comment]
@maikherbig 
Is this still an issue?

**Comment by maikherbig** [comment]
Yes, it is still an issue in Version 0.8.6. (I'm using win 7 and I reproduced the issue on another win7 PC)

**Comment by phidahl** [comment]
With Version 9.0 I cannot reproduce this behavior.

**Comment by paulmueller** [comment]
@maikherbig Could you please check whether this issue still exists in the development version? It might have been resolved by #253.

https://ci.appveyor.com/api/buildjobs/b6nm7r5b4029lg62/artifacts/.appveyor%2FOutput%2FShape-Out_0.9.6.post9_win_64bit_setup.exe

If not: When you hit "SHIFT+ENTER", does that correctly redraw the panel?

**Comment by paulmueller** [comment]
Please reopen if this is not resolved in 0.9.7.
