### ISSUE TITLE
Error when exporting all data to fcs

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/ShapeOut#215]
This is causing trouble on Gelas Macbook:

### General information
- Operating System:  Windows 7 in VM on MacOS
- ShapeOut version: ShapeOut 0.8.4 or 0.8.3.dev5
- ShapeOut install: Windows 64bit installer 

### Steps to reproduce the problem
e.g.
1. Open Shapeout
2. click Export Data
3. All event Data (.fcs)
4. Select all Data

### Expected behavior
Data is saved in .fcs file(s)

### Actual behavior
There is an error message

```
Traceback (most recent call last):
    File "shapeout\gui\export.py", line 144, in OnBrowse
    File "shapeout\gui\export.py", line 187, in export
    File "site-packages\dclab\rtdc_dataset\export.py", line 132, in fcs
    File "site-packages\fcswrite\fcswrite.py", line 136, in write_fcs
ValueError: cannot convert float NaN to integer
```

**Comment by paulmueller** [comment]
Thanks for reporting this bug in such detail. The "NaN" values might be produced by e.g. computation of the Young's modulus. I already have an idea how to fix this, but I cannot reproduce this bug with my standard datasets. Could you please point me to the location of the dataset with which this error occurs (e.g. on the group drive)? Please also post any preprocessing steps you are applying.

**Comment by felix-r** [comment]
Sorry for late response. You can find the .zmso file here:
smb://biotec-files.biotec.tu-dresden.de/guck_rtdc/experiments_16_17/20171211_Gela_contrast_agents/Neutro_GdCl3_vs_Ctrl.zmso

**Comment by paulmueller** [comment]
Thank you, but I need the actual data (folders containing tdms files). I do not have access to all the data that the session refers to (e.g. ``\\Mac\Home\Documents\Contrast_argents\Control_samples\101017_Martin_control\Online``).
I cannot reproduce the bug with the data in the folders "GdCl3" and "untreated_CTRL".

**Comment by felix-r** [comment]
Sorry again for late response. I didn't realise that some the data isn't on the server. Gela now put all the data into this folder:
\\biotec-files\guck\Members\Gela\Angela Berlin\contrast_agents_final

I hope this helps and sorry that this progresses so slowly.

**Comment by paulmueller** [comment]
I can reproduce this bug and fixed it in https://github.com/ZELLMECHANIK-DRESDEN/fcswrite/commit/a086267a7cb7dd3f284d0da8ab150bfff703b3d0.
If you can test it with the current development version: https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.875/job/3393b67520ft1xqj/artifacts
