### ISSUE TITLE
LMM Analysis on MacOs

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#217]
### General information
- Operating System: MacOs
- ShapeOut version: ShapeOut 0.8.5
- ShapeOut install: from pip

### Steps to reproduce the problem
e.g.
1. Open Shapeout
2. Analyze dataset with 2 repetitions, with treatment and control
(Contact Martin for details)

### Expected behavior
ShapeOut outputs results of LMM.

### Actual behavior
There is an error message

![pastedgraphic-1](https://user-images.githubusercontent.com/12835020/39417582-918a6d4a-4c55-11e8-8dec-00075da34dd6.png)

**Comment by paulmueller** [comment]
I think I fixed it in the above commit. Please reopen this issue if this happens again.
