### ISSUE TITLE
Choosing different colomaps for scatterplots

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/ShapeOut#239]
We currently had a discussion about colormaps and think it would be useful if one could choose between different colormaps for the scatterplots than 'jet', like the current matplotlib default 'viridis'. Maybe it is feasible if the user puts the name of the colormap in a textbox and can look up in the matplotlib docs about the possibilities. This shouldn't take too much effort to implement.

**Comment by paulmueller** [comment]
Thanks. As matplotlib currently isn't a dependency, we will need a workaround.

**Comment by maikherbig** [comment]
It looks like there are several colormaps already implemented in chaco. Also viridis, which is the one I am mostly interested in :)
https://github.com/enthought/chaco/blob/master/chaco/default_colormaps.py

**Comment by paulmueller** [comment]
Oh, I was not aware that viridis is in chaco. Unfortunately, it is not in chaco 4.5.0 (with which ShapeOut is built). I already added a combo box for choosing the colormap. Let me see what I can do to include viridis (either via backporting or via upgrading chaco).

**Comment by paulmueller** [comment]
The "viridis" colormap will be available in ShapeOut 0.9.3. You can download the development version here: https://ci.appveyor.com/project/paulmueller/shapeout/builds/24697981/job/as3smyr6dhe0x3jn/artifacts

**Comment by felix-r** [comment]
Thank you!
