### ISSUE TITLE
Integer division for aspect ratio of bounding box?

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/ShapeOut#241]
I just wanted to plot the aspect ratio and found that all the values are integers. You can see the results in the image I attached. Also when you export the data the values are integer only.
If you want to reproduce this you can use data from this sample folder: 
\\biotec-files\guck_rtdc\experiments_18_19\20190328_Felix_RBCs_Glutaraldehyde\CTRL

![image](https://user-images.githubusercontent.com/19806005/58095924-41478480-7bd4-11e9-8974-895eaa3c4d99.png)

**Comment by paulmueller** [comment]
It is reproducible. After investigating the data file with HDFView, I noted that the "aspect" feature only contains integer values (although the data type is float). After removing this particular feature (which triggers a re-computation by dclab), the plot appears correctly:
![image](https://user-images.githubusercontent.com/2853022/58102871-53302400-7be2-11e9-9c79-1bdf74fa0bc6.png)

@phidahl The data file was generated by Shape-In 2.0.6. I have another file generated by Shape-In 2.0.5 which does not exhibit this bug. Could this be a regression?

**Comment by paulmueller** [comment]
@phidahl If this bug only affects certain versions of Shape-In (specific values in the "setup:software version" attribute), then I could also implement a universal workaround in dclab.

**Comment by phidahl** [comment]
Yes, there was a wrong variable cast in the C++ code. Thanks for telling.
The following versions >2.0.6 will be fixed.

**Comment by paulmueller** [comment]
@phidahl: Just to be sure: This only affects version 2.0.6?

**Comment by felix-r** [comment]
@phidahl : I guess this also affects the filtering during the measurement? Say I set an aspect filter of 1.5 values up to 1.99 will still fall into the gate?

**Comment by phidahl** [comment]
Filtering is only affected for soft-gates, but not for hard-gates.
We are working on an update..

**Comment by paulmueller** [comment]
Meanwhile, I have implemented a fix in dclab: https://github.com/ZELLMECHANIK-DRESDEN/dclab/commit/e22a431850708d5e7e81bc4ead0618c9e8022e5a

I have triggered a new build of ShapeOut. Once it is finished, you can download it by clicking on "Artifacts":
https://ci.appveyor.com/project/paulmueller/shapeout/build/job/jnfm2nicet4owkuk

**Comment by phidahl** [comment]
I am sorry. The affected Versions are 2.0.6 and 2.0.7 (I wronlgy assumed that the affected data came from a up-to-date setup)

Version 2.0.8 was distributed to all lab PCs yesterday. So this issue should be solved.

**Comment by phidahl** [comment]
Could we release ShapeOut with this change already? I think it is important enough.

**Comment by paulmueller** [comment]
Here is the release candidate: https://ci.appveyor.com/api/buildjobs/mtgqdhw7rqgogqfn/artifacts/.appveyor%2FOutput%2FShape-Out_0.9.2.post16_win_64bit_setup.exe
