### ISSUE TITLE
IndexError in lin_mix_mod.py line 511

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#248]
This error happens when performing an lmm analysis for volume in ShapeOut for some sample combinations (for some others it works).

![Error_lmm_volume-1](https://user-images.githubusercontent.com/2853022/62376722-92171a00-b541-11e9-9381-83c8a77b92af.PNG)

The data are located at MPL ``guck\Members\Marta\Vimentin\lmm_analysis\Wt_VimKO_Filtered\Wt_VimKO.zmso``

**Comment by paulmueller** [comment]
@maikherbig Maik, did see this type of error before?
It looks like R does not return the correct number of coefficients. The line affected is: https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/blob/0.9.5/shapeout/lin_mix_mod.py#L511

Could this be a ``nan``-value issue?

**Comment by paulmueller** [comment]
Subscribe @MartaUrb

**Comment by maikherbig** [comment]
Yes, this is a nan issue.
For example look at
\20170825_Marta_DC_VimKO_d11\02_VimKO_cnt\Online\M2_0.320000ul_s.tdms
->Cell track->time: the first entry is 119, the second 166
Then look into the contours file and you will see that it starts like this:
Contour in frame 166 
( 157 , 32 )
( 156 , 33 )
...
Apparently, the first conotur (time 119) is missing. Hence, no volume or principal inertia ratio can be calculated. Five of Martas files are affected.
One can circument the issue in ShapeOut by using a filter for volume from -999999999 to 9999999. Then, the filter throws out the nan-event and lmm runs nicely :)

**Comment by paulmueller** [comment]
OK, so a fix in ``lin_mix_mod.py`` would be to remove all ``nan``/``inf`` values in the arrays given to ``linmixmod`` in ``xs``?

**Comment by MartaUrb** [comment]
Thank you guys for stepping in! And especially thank you Maik for the
workaround! You are the best!

**Comment by paulmueller** [comment]
Thank you for your help. This will be fixed in the next release of Shape-Out.
