### ISSUE TITLE
Incorporate new logo

### ISSUE THREAD

**Issue by paulmueller** [ZellMechanik-Dresden/ShapeOut#25]
I believe the splash screen should be without transparency, because the image is so sparse.

![logo_zmd_rgb](https://cloud.githubusercontent.com/assets/2853022/10447027/d75e6aa4-7180-11e5-968a-1616c67221db.png)

**Comment by paulmueller** [comment]
@Naven2812 
Is this logo a trademark? Should it be excluded from the GPL?
e.g. https://www.blender.org/about/logo/

**Comment by Naven2812** [comment]
Yes, please exclude.
