### ISSUE TITLE
Adding version of shapeout used to the file name/content when exporting extended tsv / fcs files

### ISSUE THREAD

**Issue by MartaUrb** [ZELLMECHANIK-DRESDEN/ShapeOut#250]
I am trying to keep track of that for myself but I would find it great if there would be a stamp in the file name or in some extra row of the file stating which ShapeOut version was used to export tsv/fcs file. Since ShapeOut is constantly evolving and sometimes major changes occur (like the update of LUT for elastic modulus) I would find it very useful to be able to tie each exported file to the exact version used. Do you think that would be of interest to other users?

**Comment by paulmueller** [comment]
This will be available in the next release. In the meantime you may use this build:

https://ci.appveyor.com/api/buildjobs/ctpna8irfwe9yfec/artifacts/.appveyor%2FOutput%2FShape-Out_0.9.5.post12_win_64bit_setup.exe

- for .fcs files, the version of Shape-Out is stored in the primary TEXT section (meta data)
- for .tsv files, the version of Shape-Out is stored at the beginning of the file
