### ISSUE TITLE
wishlist: include export of fluorescence track

### ISSUE THREAD

**Issue by KarenTessmer** [ZELLMECHANIK-DRESDEN/ShapeOut#254]
### General information
- Operating System: Windows 10
- ShapeOut version: ShapeOut 0.9.6
- ShapeOut install: Windows 64bit installer

### Desired Functionality
it would be cool to be able to also export the fluorescence trace as image

**Comment by paulmueller** [comment]
Because the focus of development has shifted to Shape-Out 2, this bug will not be fixed in Shape-Out 1. Please consider installing Shape-Out 2 (https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/releases/latest). Export of the fluorescence image is implemented in Shape-Out 2 (Quick View).
