### ISSUE TITLE
wishlist: export plots as .png

### ISSUE THREAD

**Issue by KarenTessmer** [ZELLMECHANIK-DRESDEN/ShapeOut#255]
### General information
- Operating System: Windows 10
- ShapeOut version: ShapeOut 0.9.6
- ShapeOut install: Windows 64bit installer

### Desired Functionality
When I export plots, I can only do so as .pdf. It would be cool to get them separately as .png.

![save_plot_as_pdf](https://user-images.githubusercontent.com/57484581/68381940-01109a00-0153-11ea-98d9-3d72af134c3a.PNG)

**Comment by paulmueller** [comment]
Unfortunately this functionality is currently broken (https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/issues/62). I will leave this issue open though for future reference.

**Comment by paulmueller** [comment]
Because the focus of development has shifted to Shape-Out 2, this bug will not be fixed in Shape-Out 1. Please consider installing Shape-Out 2 (https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/releases/latest). Shape-Out 2 can export plots as .png.
