### ISSUE TITLE
wishlist: include experiment title in plot are

### ISSUE THREAD

**Issue by KarenTessmer** [ZELLMECHANIK-DRESDEN/ShapeOut#256]
### General information
- Operating System: Windows 10
- ShapeOut version: ShapeOut 0.9.6
- ShapeOut install: Windows 64bit installer

### Desired Functionality
It would be helpful if it was possible to include a title of the experiment in the plot area.

**Comment by paulmueller** [comment]
Because the focus of development has shifted to Shape-Out 2, this bug will not be fixed in Shape-Out 1. Please consider installing Shape-Out 2 (https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/releases/latest). Shape-Out 2 shows experiment titles in the plot area.
