### ISSUE TITLE
wishlist: activate polygon filter in all samples

### ISSUE THREAD

**Issue by KarenTessmer** [ZELLMECHANIK-DRESDEN/ShapeOut#257]
### General information
- Operating System: Windows 10
- ShapeOut version: ShapeOut 0.9.6
- ShapeOut install: Windows 64bit installer

### Desired Functionality
When creating a new polygon filter, only the first filter created is applied to all the samples that are being analyzed. When manually activating the filter for all samples via the dropdown menu, it's easy to overlook samples. It would be helpful to have an option to un-/activate a polygon filter for all samples at the time.

**Comment by paulmueller** [comment]
Thanks for your input. This adds to https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/issues/95.
Please note that I will give this low priority because of the development of Shape-Out 2.

**Comment by paulmueller** [comment]
Because the focus of development has shifted to Shape-Out 2, this bug will not be fixed in Shape-Out 1. Please consider installing Shape-Out 2 (https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/releases/latest). Shape-Out 2 handles filters much better.
