### ISSUE TITLE
newcomer's question: how to add labels to issues? 

### ISSUE THREAD

**Issue by KarenTessmer** [ZELLMECHANIK-DRESDEN/ShapeOut#258]
Heyo, 
I'm entirely new to github and would like to label the issues I posted about ShapeOut. However, I have no idea how to do that. When I look at the repository, there are no checkboxes next to the created issues, so I cannot activate them to assign them a label. Is there another way to do that? Or is that not possible for everyone?
Thanks for the info, 
Karen

**Comment by paulmueller** [comment]
This is a good idea. Currently only owners of the repository can do that. Looks like this is possible via the issue template (https://github.com/isaacs/github/issues/148). I will take a look.

**Comment by paulmueller** [comment]
You should have received an invitation to the Collaborators team. Once you join, you will be able to edit issue labels (amongst other things).
