### ISSUE TITLE
A new bug in ShapeOut 0.9.7

### ISSUE THREAD

**Issue by puya-shalchi** [ZELLMECHANIK-DRESDEN/ShapeOut#260]
### General information
- Operating System: Windows 10
- ShapeOut version: ShapeOut 0.9.7
- ShapeOut install: Windows 64bit installer

### Desired functionality

Thanks for the update! It´s great that it´s now possible to create many filters for different samples without being interrupted because of the loading time of each filter. 
But now to my actual problem. When creating polygon filters it´s not possible anymore to look at each cell by going over it with the mouse. It would be great if could fix that. 
Thanks!

**Comment by paulmueller** [comment]
Thanks for reporting. Fix is underway.
