### ISSUE TITLE
All .rtdc files from one folder assigned to same sample (when not the case)

### ISSUE THREAD

**Issue by MartaUrb** [ZELLMECHANIK-DRESDEN/ShapeOut#262]
### General information
- Operating System: Windows7
- ShapeOut version: ShapeOut 0.9.7
- ShapeOut install: Windows 64bit installer

### Steps to reproduce the problem
1. Load a folder containing multiple .rtdc files with different 'sample' attribute
2. Check the structure of displayed samples in the sample panel on the left

### Data files
> I have seen it for .rtdc files, but probably works same for .tdms
> as a sample dataset "download all" files from 
https://figshare.com/articles/Real-time_deformability_cytometry_reference_data/7771184 
> unzip, load the 7771184 folder to shapeOut

### Expected behavior
The data files should be structured like this:

>calibration_beads
	- M1 channel 0.06000 
>CD34_HSPC
	- M1 channel 0.06000 
>leukocytes
	- M1 channel 0.06000 
>reticulocytes
	- M1 channel 0.06000 

### Actual behavior
What ShapeOut displayes in the sample panel on the left is:

>calibration_beads
	- M1 channel 0.06000 
	- M1 channel 0.06000 
	- M1 channel 0.06000 
	- M1 channel 0.06000

**Comment by paulmueller** [comment]
I fixed it in the development version (please test):

https://ci.appveyor.com/api/buildjobs/xp9dsapnxq6sjpxp/artifacts/.appveyor%2FOutput%2FShape-Out_0.9.8.post1_win_64bit_setup.exe

**Comment by MartaUrb** [comment]
Works! 

I have copied few datasets here: smb://biotec-files/guck_transitional/members/Marta/Sorting_manu/Ordered Data/test_pulled 

And the screenshots of the out comes of loading this folder to ShapeOut 0.9.7 and 0.9.8_post 1 are attached.

[SampleName_OneFolder_ShapeOut_0 9 7](https://user-images.githubusercontent.com/15630027/69436336-1b449d80-0d39-11ea-82bf-9a4b453fe5b1.JPG)
![SampleName_OneFolder_ShapeOut_0 9 8_post1](https://user-images.githubusercontent.com/15630027/69436337-1b449d80-0d39-11ea-8deb-f7605c530949.JPG)
