### ISSUE TITLE
Desired functionality: Copy paste data table 

### ISSUE THREAD

**Issue by puya-shalchi** [ZELLMECHANIK-DRESDEN/ShapeOut#263]
Operating System: Windows 10
ShapeOut version: ShapeOut 0.9.8
ShapeOut install: Windows 64bit installer

Desired functionality 

Could you please implement the possibility to copy and paste the whole data table from the statistics tab? 

Thank you very much and wish you all the best for 2020!

**Comment by paulmueller** [comment]
Because the focus of development has shifted to Shape-Out 2, this bug will not be fixed in Shape-Out 1. Please consider installing Shape-Out 2 (https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut2/releases/latest)-
