### ISSUE TITLE
Error no. of arguments contour plot

### ISSUE THREAD

**Issue by chrherold** [ZELLMECHANIK-DRESDEN/ShapeOut#265]
Error message appears in version 1.0.1 and 1.0.2 when trying to activate contour plot.

<img width="772" alt="image" src="https://user-images.githubusercontent.com/13899168/74715618-0fc81c00-522d-11ea-9cf0-4261b6bf19f2.png">

**Comment by paulmueller** [comment]
:scream: this was introduced by c702b19ae4cc2efe2be5b2cecdd1a20d8016b90
