### ISSUE TITLE
Export computed statistics error with superscript parameters

### ISSUE THREAD

**Issue by jarogumulec** [ZELLMECHANIK-DRESDEN/ShapeOut#267]
### General information
- Operating System: Windows 10, two machines with up to date windows 64bit, both with Czech language
- ShapeOut version: e.g. ShapeOut 1.0.3
- ShapeOut install: github releases

### Steps to reproduce the problem
1. Open Shapeout
2. Search for a dataset
3. Select a dataset and press "Analyze"
4. export data -computed statistics (but only when one of the outputs selected includes superscript (um2, etc.) following error message occur. when the output is set to anything different without superscript ("deformaiton", etc) no problem with export.
5. the same problem also with batch-statistical summary

(otherwise plotting is OK - cannot just export).
No such problem observed in MPL instalations.

### Data files
no dependence on data files

### Expected behavior
ShapeOut exports the statistical summary

### Actual behavior
There is an error message
![error_shapeout103](https://user-images.githubusercontent.com/29793471/77297460-961ec480-6ce9-11ea-96b2-d7d63a2c3fe0.png)

**Comment by paulmueller** [comment]
Thanks, this is related to the standard encoding being central/eastern european. I wil investigate.

**Comment by paulmueller** [comment]
Could you please test whether the following build works for you?

https://ci.appveyor.com/api/buildjobs/45nx0pv00qaowq07/artifacts/.appveyor%2FOutput%2FShape-Out_1.0.4.post1_win_64bit_setup.exe

PS: You might want to consider Shape-Out 2 https://shapeout2.readthedocs.io/en/stable/sec_interface.html#differences-to-shape-out-1

**Comment by jarogumulec** [comment]
Dear Paul, 
that solved the problem, thanks.
Jaromir
