### ISSUE TITLE
Failed to link documentation correctly when called within the program

### ISSUE THREAD

**Issue by chrherold** [ZELLMECHANIK-DRESDEN/ShapeOut#269]
Shape-Out 1.0.6

Since documentation is at stage 1.0.3 the link used in Help/Documentation within the program leads to a non-existing page.

**Comment by paulmueller** [comment]
Thank you, I already fixed this with 6fb164604ce69ae2c59be3d5318c1bf11fb9d691.
If you think this is critical, we can make a new release.
