### ISSUE TITLE
"Contour fix scale" in "Contour tab" is not working for y

### ISSUE THREAD

**Issue by MaikH88** [ZellMechanik-Dresden/ShapeOut#31]
When this option is checked, only the Contour accuracy of area is fixed. Contour accuracy of Def is not.

**Comment by paulmueller** [comment]
I cannot reproduce this behaviour. Could you please check again? Did you hit apply in the "Contour Plot" tab after checking "Contour Fix Scale"?

**Comment by paulmueller** [comment]
Closing because not reproducible. Please reopen if problem persists.
