### ISSUE TITLE
64bit builds are not working

### ISSUE THREAD

**Issue by Naven2812** [ZELLMECHANIK-DRESDEN/ShapeOut#4]
After installation of 0.43 Shape-Out crashes during start
deinstallation does not help
0.42 also does not work anymore
0.40 works

**Comment by paulmueller** [comment]
Which Windows version are you using?
Have you tried both builds 32bit and 64bit?

**Comment by Naven2812** [comment]
I am using Win7 64
I have only tried 64bit

**Comment by paulmueller** [comment]
The 32bit version should work. There is no disadvantage to the 64bit version unless you are working with extremely large data sets and are getting memory errors.

**Comment by paulmueller** [comment]
With large measurements, there is not enough memory for the 32bit built. Switch to the 64bit build by default.

**Comment by paulmueller** [comment]
I enable 64bit builds and it seems to work again:
https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.529/job/y4gn4ln1bd97t3wd/artifacts

Please reopen this issue if the problem persists.
