### ISSUE TITLE
Error when plotting fluorescence data

### ISSUE THREAD

**Issue by phidahl** [ZellMechanik-Dresden/ShapeOut#40]
I want to plot data from a tdms file with fluorescence data. (Can't upload here, but can mail it.)
If I select X: Cell size, Y: FL-3 (red) Maximum and click "Apply", I get the following error message.

(...)
File "C:\(...)build\win_shapeout\out00-PYZ.pyz\shapeout.util", line 52, in float2string_nsf
ValueError: Format specifier missing precision.

**Comment by phidahl** [comment]
I have build 1.0.194 from AppVeyor

**Comment by paulmueller** [comment]
Sorry, made a mistake. Please try the latest build.
