### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (2000,)(2281,)

### ISSUE THREAD

**Issue by MartaUrb** [ZellMechanik-Dresden/ShapeOut#43]
![image](https://cloud.githubusercontent.com/assets/15630027/11363653/738a9da4-929b-11e5-8d71-b7333732de6d.png)

**Comment by paulmueller** [comment]
It looks like something went wrong with filtering there. Could you please describe accurately what you were trying to do, so I can reproduce the problem?

**Comment by MartaUrb** [comment]
I am trying to look at the data from Phillips setup. Here is the data folder:
smb://biotec-files/guck_rtdc/experiments_14_15/20151123_Marta_F-Class <smb://biotec-files/guck_rtdc/experiments_14_15/20151123_Marta_F-Class>

It just happens when I try to plot any dataset I think, try second one.

Cheers,

Marta

—

Marta Urbanska

PhD Student, Guck Lab

Technische Universität Dresden
Biotechnology Center
Tatzberg 47/49
01307 Dresden

Tel: +49 (0)351 463 40325
Email: marta.urbanska@biotec.tu-dresden.de <mailto:marta.urbanska@biotec.tu-dresden.de> 
www.biotec.tu-dresden.de <http://www.biotec.tu-dresden.de/>

**Comment by paulmueller** [comment]
I believe I fixed it. This is a regression in dclab. All versions of ShapeOut with dclab 0.1.5 should not anymore have this problem. Once the next build is done, could you please try the latest binary from there:
https://ci.appveyor.com/project/paulmueller/ShapeOut/build/artifacts

**Comment by MartaUrb** [comment]
Yes it works nice now!

Thanks :)

—

Marta Urbanska

PhD Student, Guck Lab

Technische Universität Dresden
Biotechnology Center
Tatzberg 47/49
01307 Dresden

Tel: +49 (0)351 463 40325
Email: marta.urbanska@biotec.tu-dresden.de <mailto:marta.urbanska@biotec.tu-dresden.de> 
www.biotec.tu-dresden.de <http://www.biotec.tu-dresden.de/>
