### ISSUE TITLE
Frame Numbering in fRT-DC files different

### ISSUE THREAD

**Issue by phidahl** [ZellMechanik-Dresden/ShapeOut#46]
in shapeout/plot.py line 292

video.set(cv2.CAP_PROP_POS_FRAMES, actual_sel-1)

The -1 has to be omitted for fRT-DC files, because frame numbering starts at 0. Is it possible to do this if there is any of the fluorescence channels detected in the tdms file?

**Comment by paulmueller** [comment]
Is there any other way to determine this, except checking for fluorescence channels?
Does the tdms file contain the correct frame number?

**Comment by phidahl** [comment]
I could put the following line into the the file "XX_para.ini" file:

avi skip first event = 0

This means that the first frame of the avi file (number 0) is also corresponding to the first event in the tdms file. If not so, there is no image for the first event in the tdms file. (This is the case for all normal RT-DC measurements)

**Comment by paulmueller** [comment]
So, to not break previous measurements, the default would be `avi skip first event = 1`?
Where should we put it - I think the `[General]` section would fit best.

**Comment by phidahl** [comment]
Yes this would be fine.
Or would you call it differently? Maybe it would be more general if the number says how many events are missing in the avi file.

**Comment by paulmueller** [comment]
`avi frame offset`?

**Comment by phidahl** [comment]
okay

**Comment by paulmueller** [comment]
I misunderstood the problem. There is actually an image **missing** in the video file. We can use the keyword `video frame offset` anyway.

Then we also need to catch the exception that is raised when `actual_sel==0`!

```python
ERROR:traits:Exception occurred in traits notification handler for object: <chaco.array_data_source.ArrayDataSource object at 0x7ff916e1d470>, trait: metadata_changed, old value: <undefined>, new value: True
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 520, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/usr/lib/python2.7/dist-packages/traits/trait_notifiers.py", line 483, in dispatch
    handler( *args )
  File "shapeout/gui/plot.py", line 310, in OnMouseScatter
KeyError: 30959.0
```

I will finish this soon.
