### ISSUE TITLE
Button to hide data point

### ISSUE THREAD

**Issue by DerDeef** [ZellMechanik-Dresden/ShapeOut#47]
If the image shows tracked dirt or something, it should be possible to hide and exclude (not delete) the data point for analysis.

**Comment by paulmueller** [comment]
This would boil down to a filter array for manual filtering in dclab, i.e. `dclab.RTDC_DataSet._filter_manual`.

**Comment by paulmueller** [comment]
This option could be implemented next to the spin control of issue #49.
