### ISSUE TITLE
Index number to all data points in the plot...

### ISSUE THREAD

**Issue by DerDeef** [ZellMechanik-Dresden/ShapeOut#49]
..this way one can find specific data points later

**Comment by paulmueller** [comment]
What do you mean by index. Display a number next to each and every point in the plot?

**Comment by DerDeef** [comment]
Maybe next to each image. If a picture is interesting than I can write this number down.

**Comment by paulmueller** [comment]
Implement this as a spin control that lets the user choose a particular cell.

**Comment by paulmueller** [comment]
Also display information of the plot parameters (current plot axes) for the event.
