### ISSUE TITLE
order of plots

### ISSUE THREAD

**Issue by DerDeef** [ZellMechanik-Dresden/ShapeOut#51]
Sorting and grouping of plots on the panel would be helpful. E.g. by drag and drop or some kind of numbering.

**Comment by paulmueller** [comment]
In addition, the order of plots should remain after saving and loading a session.

**Comment by paulmueller** [comment]
Could anyone please test this binary and let me know whether it runs on Windows. I currently only have acces to a linux machine.

https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.287/artifacts

Thanks!

**Comment by DerDeef** [comment]
how does it work? how to change the order?

**Comment by paulmueller** [comment]
In the Plotting tab. Plot order can be changed by dragging and dropping the rows in the displayed table.
