### ISSUE TITLE
polygon filter does not reset

### ISSUE THREAD

**Issue by DerDeef** [ZellMechanik-Dresden/ShapeOut#53]
1. I guess this is a bug? If I want to reset a polygon filter, nothing happens in the plot.
2. Also removing the polygon doesnt change something.

**Comment by paulmueller** [comment]
1. Technically this might be a bug. What you are resetting are the filter settings. You have to de-select each polygon filter for them to be removed from the plot.
2. The plot changes if you hit "Apply"

**Comment by DerDeef** [comment]
ahhhhhhh
thx
