### ISSUE TITLE
FCS Export for FlowJoe

### ISSUE THREAD

**Issue by DerDeef** [ZELLMECHANIK-DRESDEN/ShapeOut#54]

**Comment by paulmueller** [comment]
Note to myself: @phidahl wrote Python code for exporting to the fcs file format. Might be a good idea to create a Python library from that and upload it to pypi.

**Comment by paulmueller** [comment]
The fcswriter is implemented here:

https://github.com/ZELLMECHANIK-DRESDEN/fcswrite
