### ISSUE TITLE
fRT-DC fluorescence analysis not working

### ISSUE THREAD

**Issue by ahjanee** [ZELLMECHANIK-DRESDEN/ShapeOut#55]
Hi Paul,

we tried to analyse fRT-DC data with ShapeOut but as soon as we try to open the fluorescent parameter, ShapeOut starts working but gets stuck (though it doesn't display any error message). We would like to be able to load and dislay the fluorescence in a similar manner as deformation and size (especially with contour lines). Interestingly, there have been a few times when the analysis was working, but not consistently.

Many thanks in advance,
Maria & Ariane

**Comment by paulmueller** [comment]
@phidahl wasn't this issue solved before?

@ahjanee did you try the latest dev version? https://ci.appveyor.com/project/paulmueller/ShapeOut/build/artifacts

**Comment by phidahl** [comment]
I think this problem is not occuring for all data. My idea about this issue is, that the controur finding might not work if the point are concentrated in a very small area (which might be the case for some fl. data)
The workaround so far was to switch of drawind the contours.

**Comment by paulmueller** [comment]
Please let me have an example data set where this hang/problem occurs.
