### ISSUE TITLE
log scale (fRT-DC related)

### ISSUE THREAD

**Issue by katpla** [ZellMechanik-Dresden/ShapeOut#56]
Hi,

it would be great if we could display the fluorescence data on log axis

Cheers
K

**Comment by paulmueller** [comment]
@phidahl You mentioned some kind of mixed-linear-log-plot that is frequently used in flow cytometry. Could you please point me to an example plot or anything that I could use to reproduce a similar behavior?

**Comment by katpla** [comment]
Hello Paul,

I am very sorry for the late response.

I did not really mean the lin/log plot. I wanted just an option to change
between linear scale and logarithmic scale (so a tick box somewhere which
makes it possible to display data on log plot)

There are some fancy lin/log plots for FACS but I do not think they will be
useful for fRT-DC users.

Best
K



2016-05-16 17:24 GMT+02:00 Paul Müller <notifications@github.com>:

> @phidahl <https://github.com/phidahl> You mentioned some kind of
> mixed-linear-log-plot that is frequently used in flow cytometry. Could you
> please point me to an example plot or anything that I could use to
> reproduce a similar behavior?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ZellMechanik-Dresden/ShapeOut/issues/56#issuecomment-219454726>
>



-- 
pozdrawiam k

**Comment by phidahl** [comment]
I tested it, it works fine. Except of the fact that there are to many ticks on the axes. It would be sufficient to have one tick per decade (1, 10, 100, 1000, ... )

Thanks a lot,
Philipp

**Comment by paulmueller** [comment]
The contour plot is automatocally disabled when using the log scale because of  a bug in chaco.
