### ISSUE TITLE
RTDC Acquisition software forgets to write "Region" tag

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/ShapeOut#58]
Some measurements (recorded with the LabView setup) cannot be loaded with ShapeOut, because the `Region` tag in the `*_para.ini` files is missing (`Region = ""` default value?). No error is displayed to the user, because the directory is searched recursively in a separate thread. On a command line, this error pops up:

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "shapeout/gui/gaugeframe.py", line 82, in run
    res=result.get(timeout=.1)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
KeyError: 'Region'
```
A workaround is setting the region manually in the .ini file.

@phidahl @Naven2812 @DerDeef
Could you please fix this mistake made by the acquisition software? I believe it would not make sense to address this issue in ShapeOut.

**Comment by Naven2812** [comment]
Hi Paul,

danke. Kannst Du uns den Datensatz dazu schicken?

Lieben Gruss,

Oli

On 22/03/2016 15:14, Paul Müller wrote:
>
> Some measurements (recorded with the LabView setup) cannot be loaded
> with ShapeOut, because the |Region| tag in the |*_para.ini| files is
> missing (|Region = ""| default value?). No error is displayed to the
> user, because the directory is searched recursively in a separate
> thread. On a command line, this error pops up:
>
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
>     self.run()
>   File "shapeout/gui/gaugeframe.py", line 82, in run
>     res=result.get(timeout=.1)
>   File "/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
>     raise self._value
> KeyError: 'Region'
>
> A workaround is setting the region manually in the .ini file.
>
> @phidahl <https://github.com/phidahl> @Naven2812
> <https://github.com/Naven2812> @DerDeef <https://github.com/DerDeef>
> Could you please fix this mistake made by the acquisition software? I
> believe it would not make sense to address this issue in ShapeOut.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ZellMechanik-Dresden/ShapeOut/issues/58>
>

-- 
Dr. Oliver Otto

Technische Universität Dresden
Biotechnology Center
Tatzberg 47/49
01307 Dresden

Tel: +49 (0)351 463 40324
Fax: +49 (0)351 463 40342
Email: oliver.otto@biotec.tu-dresden.de
www.biotec.tu-dresden.de

**Comment by paulmueller** [comment]
As there were no other reports, I assume this is fixed by now.
