### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by DerDeef** [ZellMechanik-Dresden/ShapeOut#59]
Is it possible to implement an auto-updater for the software? This would be useful for user without administration right on their university computers.

**Comment by paulmueller** [comment]
This is not possible. However, it should be possible to install ShapeOut to the user directory and not require admin rights. I am experimenting with that right now.

**Comment by paulmueller** [comment]
@DerDeef 
It works. Installing ShapeOut from now on does not require admin rights anymore. This is a better solution than an Auto updater, because people might want to stick to a certain version of ShapeOut.
If you agree, please close this issue.

**Comment by paulmueller** [comment]
If you don't agree, please reopen this issue.
