### ISSUE TITLE
Add Statistics tab

### ISSUE THREAD

**Issue by paulmueller** [ZellMechanik-Dresden/ShapeOut#6]
For each gated and plotted data set (e.g. with polygon filters), show statistical information:

- mean
- median
- mode
- std

... more @Naven2812 ?

Add checkbox to display results for local or global gating.

**Comment by phidahl** [comment]
add function to create boxplot-comparision of different populations (either from different measurements or gated from one measurement)

**Comment by paulmueller** [comment]
Please explain.
Please include an exemplary graph that you would like to have.

**Comment by paulmueller** [comment]
@phidahl 
I am closing this because I think it is a duplicate of #7
