### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by phidahl** [ZellMechanik-Dresden/ShapeOut#61]
There is an error appearing in AppVeyor:

rror: MD5 sums mismatch for download: http://repo.continuum.io/pkgs/free/win-32/mkl-11.3.1-0.tar.bz2 (6630258206482847d9e7af500a4c95cb != 52818e34fc742ca29649d88994258663)
Command exited with code 1

and last time:

rror: MD5 sums mismatch for download: http://repo.continuum.io/pkgs/free/win-32/freetype-2.5.5-vc9_0.tar.bz2 (f436ee7b29d97e4c7501eb084eb0ac92 != 2ba79f0e56db19388956a57463e8148c)
Command exited with code 1

**Comment by paulmueller** [comment]
I have observed the same problem. There seems to be some kind of problem with the internet connection that appveyor uses? I solved the problem by rebuilding the commit. After several tries it works. I gave the ZellMechanik-Dresden GitHub collaborators administrator rights. If you log in "with GitHub" on Appveyor, you should be able to rebuild the commit directly from within Appveyor.

Sorry for the inconvenience, but right now I don't see any other solution.

**Comment by paulmueller** [comment]
It seemed to be a problem with the old Miniconda version that was used for the build process. ShapeOut is now using the Miniconda installation that comes with Appveyor (``C:\\Miniconda``).
