### ISSUE TITLE
Display fluorescence curve of individual cells.

### ISSUE THREAD

**Issue by paulmueller** [ZellMechanik-Dresden/ShapeOut#65]
@phidahl Could you please provide me with a code snippet that extracts the required fluorescence information and point me to an example data set that contains such separate fluorescence curve tdms files?

**Comment by phidahl** [comment]
I tested this enhancement and it seems to work stable.
Could you maybe change the colors of the lines in the plot to the following scheme:

FL-1: green
FL-2: orange
FL-3: red
