### ISSUE TITLE
Gray dot in scatterplot are too large

### ISSUE THREAD

**Issue by phidahl** [ZellMechanik-Dresden/ShapeOut#69]
Cells that are filtered out are represented as gray dots.
In the PDF Those seem to be much larger than the colored dots and we are not sure whether the gray dots are in front of the colored. This wouldn't make sense.

Could you put the colored in front of the gray dots?
And could you make it possible to make the gray dots smaller?

Thanks :)

**Comment by paulmueller** [comment]
I fixed the size problem in develop. On Ubuntu, the grey dots are behind the colored ones. Is this a Windows problem?
[1.pdf](https://github.com/ZellMechanik-Dresden/ShapeOut/files/284085/1.pdf)
