### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by MaikH88** [ZELLMECHANIK-DRESDEN/ShapeOut#71]
Every once in a while an error message pops up (see attachment). Before this error comes the PC is calculating very long, even when KDE=none (this should go very fast
![shapeout_0 5 8_error](https://cloud.githubusercontent.com/assets/14074051/15774437/88385fde-297c-11e6-8b3a-cc9113d7153e.jpg)
)

**Comment by paulmueller** [comment]
Could you please give me the version number of dclab that is listed in Help->Software?

https://github.com/ZellMechanik-Dresden/dclab/blob/master/dclab/rtdc_dataset.py#L152

There might be a problem with the computation of the contours. Does this error occur only for specific data sets or is it completely random?

**Comment by paulmueller** [comment]
I am closing this issue as I think I have solved it in 0.6.5
