### ISSUE TITLE
Paths stored in session file

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#80]
When a session file is transferred to another computer, the path to the .tdms files probably won't be correct anymore because of the different environment.
Because of that it would be very useful to ask the user to specify the correct path in that case and repair the path in the session file. There is also a hash of the data in the session file, so it would be possible to verify that the correct path was selected.

**Comment by paulmueller** [comment]
Todo:
[ ] also save relative paths in index file (people might move the measurement around with the session)
[ ] check that all dialogs are destroyed properly
