### ISSUE TITLE
No update of event number when applying filter

### ISSUE THREAD

**Issue by chrherold** [ZELLMECHANIK-DRESDEN/ShapeOut#85]
In 0.6.1dev10 pressing the apply button after filtering in the "Filtering" tab does not change the event number displayed for the plots.

Apply buttons in other tabs do.

**Comment by paulmueller** [comment]
Thanks for reporting. This is a regression that was introduced by fixing #84. I fixed it.
https://ci.appveyor.com/project/paulmueller/shapeout/build/1.0.403/artifacts
Please let me know if you find anything else.
