### ISSUE TITLE
removed events (grey dots) drawn on top of gated events (colored dots)

### ISSUE THREAD

**Issue by katpla** [ZELLMECHANIK-DRESDEN/ShapeOut#86]
Hi,

There is a small issue that the grey dots (filtered-out events) are plotted on top of the non filtered-out events in the scatter plot. It's not major, but the plots would look better if it was the other way round (this problems is visible in version 6.2)

Best
K

**Comment by phidahl** [comment]
I report that version 0.6.2.dev1 containing this fix, works correctly and the black dots are on top of the grey dots.

Thanks
Philipp
