### ISSUE TITLE
Contour Plot: Optionally do not automatically determine parameters

### ISSUE THREAD

**Issue by paulmueller** [ZellMechanik-Dresden/ShapeOut#9]
This means optionally fixing
- accuracy
- KDE parameters

**Comment by phidahl** [comment]
Would it be possible to use a simple histogram - say 20 x 20 bins for determining the densities? - I think this would be more stable than the KDE approach where the bandwidth parameters may differ between measurements.

**Comment by paulmueller** [comment]
The control "Contour Fix Scale" will fix accuracy and KDE parameters.
