### ISSUE TITLE
Improve handling of polygon filters

### ISSUE THREAD

**Issue by phidahl** [ZELLMECHANIK-DRESDEN/ShapeOut#95]
For the workflow of gating several subpopulations in children of one main plot, it would be better if the new polygon-filter would only be applied to the currently selected plot.

**Comment by chrherold** [comment]
Some Feedback: I guess changes in this particular matter will always disturb/change workflows.
But I also think that would be room for some improvements.

The current situation is that the first polygon filter created is applied to every plot automatically. All additional polygon filters are only created but not right away applied to any (not even the active plot)

@phidahl: Is your comment directed towards the case that you create several child plots and create the first polygon filter to one of them? I guess in this case it makes a lot of sense to apply it only to the selected child (and not the parent as well, as is the case now)

So my suggestion for the workflow is:

1) The first polygon filter created is directly applied to all plots but children (as is the case, to children it is applied indirectly), UNLESS (this would need a change) it is applied to any child plot. In this case it should only be applied to the selected child.

2) Any additional polygon filter should be applied to the selected plot only (no matter if child or normal plot)  (this would also be a change to the current situation as the selected plot is not automatically updated)



And here comes one more suggestion going beyond the scope of the original comment:

I got a lot of feedback saying it is very painful to always click through the drop down menu (repeatedly) to change the polygon filter application.

So here my rather radical suggestion:
Have a table of checkboxes, where rows are the plot titles (including an "select/unselect ALL" option on top) and columns are the polygon filters. 
The drop down menu could than be used for the polygon creation process as is at the moment, but would not be necessary to check or uncheck the use of a filter in a specific plot.
I guess this would make life of users much easier.
The general application workflow should still be as suggested above.
@paulmueller: Would such an implementation be possible with reasonable effort?

**Comment by paulmueller** [comment]
@chrherold I agree with you on all your points. Adding a table-like filter selection is possible. I will not give it high priority though, as effort is greater than gain in my opinion. If this is bothering a lot of users, I would give it higher priority.

**Comment by paulmueller** [comment]
...has become obsolete with Shape-Out 2.
